version: '2'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    links:
      - app:app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build:/usr/share/nginx/html:ro
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-datavolume:/data/db
  app:
    build: .
    restart: unless-stopped
    links:
      - mongo:mongo
    volumes:
      - .:/app
    command: "npm run start:dev"
volumes:
  mongo-datavolume: