version: '2'
services:
  nginx:
    image: nginx:latest    
    ports:
      - "8080:80"
    links:
      - app:app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./build:/var/www/html:ro
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-datavolume:/data/db
  app:
    build: .
    links:
      - mongo:mongo
volumes:
  mongo-datavolume: