version: "2"
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
  mongo:
    image: mongo:4.4.12
    restart: unless-stopped
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo-datavolume:/data/db
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: "npm run start:prod"
volumes:
  mongo-datavolume:
